# woohoo, yaml engineering
name: Build/deploy Lambda

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: amazonlinux:2
    steps:
    - run: yum install -y git gcc binutils clang cmake3 make zip tar libgexiv2-devel
    - run: ln -s cmake3 /usr/bin/cmake
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: |
          ~/.cargo/registry
          target
        key: cargo-${{ hashFiles('Cargo.toml') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --bin imgroll-lambda
    - run: ldd -v target/release/imgroll-lambda
    - run: mkdir -p lambda/lib && cp target/release/imgroll-lambda lambda/bootstrap && cp /usr/lib*/*exiv2*so.* /usr/lib*/libgobject*so.* /usr/lib*/libglib*so.* /usr/lib*/libgio*so.* lambda/lib/
    - run: (cd lambda && zip -y -r ../lambda.zip *)
    - uses: stcalica/update-lambda@0.0.2
      with:
        package: lambda.zip
        function-name: ${{ secrets.FUNCTION_NAME }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # the IAM user for this only needs lambda:UpdateFunctionCode on this function
